resources:
- namespace.yaml
- manager.yaml
- service_account.yaml
images:
- name: manager
  newName: victoriametrics/operator
  newTag: 0.1.0
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
