apiVersion: victoriametrics.com/v1beta1
kind: VmAgent
metadata:
  name: example-vmagent
spec:
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  # Add fields here
  replicaCount: 1
  resources:
    requests:
      cpu: "50m"
      memory: "50Mi"
  serviceAccountName: vmagent
  additionalArgs:
    memory.allowedPercent: "40"
  remoteWrite:
    - url: "http://vmsingle-example-vmsingle.default.svc:8429/api/v1/write"

