apiVersion: victoriametrics.com/v1beta1
kind: VmSingle
metadata:
  name: example-vmsingle-pvc
spec:
  # Add fields here
  retentionPeriod: "1"
  removePvcAfterDelete: true
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
