# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/operator.victoriametrics.com_vmagents.yaml
- bases/operator.victoriametrics.com_vmalerts.yaml
- bases/operator.victoriametrics.com_vmalertmanagers.yaml
- bases/operator.victoriametrics.com_vmpodscrapes.yaml
- bases/operator.victoriametrics.com_vmrules.yaml
- bases/operator.victoriametrics.com_vmservicescrapes.yaml
- bases/operator.victoriametrics.com_vmsingles.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_vmagents.yaml
#- patches/webhook_in_vmalerts.yaml
#- patches/webhook_in_vmalertmanagers.yaml
#- patches/webhook_in_vmpodscrapes.yaml
#- patches/webhook_in_vmrules.yaml
#- patches/webhook_in_vmservicescrapes.yaml
#- patches/webhook_in_vmsingles.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_vmagents.yaml
#- patches/cainjection_in_vmalerts.yaml
#- patches/cainjection_in_vmalertmanagers.yaml
#- patches/cainjection_in_vmpodscrapes.yaml
#- patches/cainjection_in_vmrules.yaml
#- patches/cainjection_in_vmservicescrapes.yaml
#- patches/cainjection_in_vmsingles.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
