- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestLoadBalancer/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/requestLoadBalancer/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/storage/properties/volumeClaimTemplate/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/storage/properties/volumeClaimTemplate/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/claimTemplates/items/properties/metadata/x-kubernetes-preserve-unknown-fields
  value: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmstorage/properties/serviceScrapeSpec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/persistentVolume/properties/volumeClaimTemplate/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/persistentVolume/properties/volumeClaimTemplate/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/claimTemplates/items/properties/metadata/x-kubernetes-preserve-unknown-fields
  value: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vmselect/properties/serviceScrapeSpec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/hpa/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/hpa/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/vminsert/properties/serviceScrapeSpec/properties
