- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/affinity/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/affinity/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/claimTemplates/items/properties/metadata/x-kubernetes-preserve-unknown-fields
  value: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/containers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/containers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/dnsConfig/items
  value:
    x-kubernetes-preserve-unknown-fields: true
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/extraEnvs/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/extraEnvs/items/properties/valueFrom
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/initContainers/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/initContainers/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/topologySpreadConstraints/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/topologySpreadConstraints/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/serviceSpec/properties/spec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/serviceSpec/properties/spec/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/volumes/items/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/volumes/items/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/startupProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/startupProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/readinessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/readinessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/livenessProbe/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/livenessProbe/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/securityContext/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/securityContext/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/serviceScrapeSpec/x-kubernetes-preserve-unknown-fields
  value: true
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/serviceScrapeSpec/properties
- op: remove
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/aPIServerConfig/properties
- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/spec/properties/aPIServerConfig/x-kubernetes-preserve-unknown-fields
  value: true
