apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributedCluster
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: vmdistributedcluster-sample
spec:
  vmAgent:
    name: vmagent-sample
  vmUsers:
    - name: vmuser-us-east-1
    - name: vmuser-us-west-2
    - name: vmuser-eu-west-1
  vmClusters:
    - name: vmcluster-us-east-1
    - name: vmcluster-us-west-2
    - name: vmcluster-eu-west-1
  clusterVersion: 1.127.0
