apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
    app.kubernetes.io/managed-by: kustomize
  name: sample-override
spec:
  vmagent:
    name: vmagent-sample
  vmauth:
    name: vmauth-sample
  zones:
    - name: us-east-1
      vmcluster:
        name: vmcluster-us-east-1
        spec:
          vmselect:
            replicaCount: 2
    - name: us-west-2
      vmcluster:
        name: vmcluster-us-west-2
        spec:
          vmselect:
            replicaCount: 2
    - name: eu-west-1
      vmcluster:
        name: vmcluster-eu-west-1
        spec:
          vmselect:
            replicaCount: 2
