apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/VictoriaMetrics/operator/config/default?ref=v0.2.0

namespace: team-a-monitoring
images:
- name: victoriametrics/operator
  newTag: v0.2.0

patches:
- manager.patch.yaml
# - manager.arm.patch.yaml # To patch for ARM images

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: monitoring-system
  patch: |-
    - op: replace
      path: "/metadata/name"
      value: team-a-monitoring
