apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# - github.com/VictoriaMetrics/operator/config/default?ref=v0.2.0
- ../../config/default

namespace: monitoring
images:
- name: victoriametrics/operator
  newTag: v0.2.0

patches:
- manager.patch.yaml

patchesJson6902:
- target:
    version: v1
    kind: Namespace
    name: default
  patch: |-
    - op: replace
      path: "/metadata/name"
      value: monitoring
