apiVersion: v1
kind: ServiceAccount
metadata:
  name: vlagent-k8s-ns-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vlagent-k8s-ns-collector
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlagent-k8s-ns-collector
subjects:
  - kind: ServiceAccount
    name: vlagent-k8s-ns-collector
roleRef:
  kind: ClusterRole
  name: vlagent-k8s-ns-collector
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: operator.victoriametrics.com/v1
kind: VLAgent
metadata:
  name: ns-collector
spec:
  resources:
    requests:
      cpu: "50m"
      memory: "350Mi"
    limits:
      cpu: "500m"
      memory: "850Mi"
  useStrictSecurity: true
  serviceAccountName: vlagent-k8s-ns-collector
  k8sCollector:
    enabled: true
    extraFields: '{"env":"dev","cluster":"staging"}'
    msgFields:
      - msg
      - message
      - log.msg
    timeFields:
      - time
      - ts
      - timestamp
  remoteWrite:
    - url: "http://vlsingle-example-0.default.svc:9428/internal/insert"
