apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: VMDistributed-sample-custom-timeout
spec:
  readyDeadline: 10m
  zoneUpdatePause: 1m
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    vmclusters:
    - ref:
        name: vmcluster-us-east-1
      spec:
        vmselect:
          replicaCount: 3
    - ref:
        name: vmcluster-us-west-2
      spec:
        vmselect:
          replicaCount: 4
    - ref:
        name: vmcluster-eu-west-1
      spec:
        vmselect:
          replicaCount: 2
