apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: sample-override-versions
spec:
  vmauth:
    name: global-vmauth
    spec:
      replicaCount: 1
  zoneCommon:
    vmagent:
      spec:
        replicaCount: 1
    vmcluster:
      name: vmcluster-%ZONE%
      spec:
        vmstorage:
          replicaCount: 1
        vmselect:
          replicaCount: 1
          image:
            tag: v1.90.0
        vminsert:
          replicaCount: 1
  zones:
    - name: us-east-1
    - name: us-west-2
    - name: eu-west-1
      vmcluster:
        spec:
          vmselect:
            image:
              tag: v1.111.0
