apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: sample-paused
spec:
  paused: true
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    - vmcluster:
        ref:
          name: vmcluster-us-east-1
        spec:
          vmselect:
            replicaCount: 3
    - vmcluster:
        ref:
          name: vmcluster-us-west-2
        spec:
          vmselect:
            replicaCount: 4
    - vmcluster:
        ref:
          name: vmcluster-eu-west-1
        spec:
          vmselect:
            replicaCount: 2
