apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: sample-override-versions
spec:
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    - vmcluster:
        ref:
          name: vmcluster-us-east-1
        spec:
          vmselect:
            image:
              tag: v1.90.0
    - vmcluster:
        ref:
          name: vmcluster-us-west-2
        spec:
          vmselect:
            image:
              tag: v1.90.0
    - vmcluster:
        ref:
          name: vmcluster-eu-west-1
        spec:
          vmselect:
            image:
              tag: v1.111.0
