apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-us-east-1
spec:
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-us-west-2
spec:
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster-eu-west-1
spec:
  vmstorage:
    replicaCount: 1
  vmselect:
    replicaCount: 1
  vminsert:
    replicaCount: 1
---
apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: VMDistributed-sample-override
spec:
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    vmclusters:
    - ref:
        name: vmcluster-us-east-1
      overrideSpec:
        vmselect:
          replicaCount: 3
    - ref:
        name: vmcluster-us-west-2
      overrideSpec:
        vmselect:
          replicaCount: 4
    - ref:
        name: vmcluster-eu-west-1
      overrideSpec:
        vmselect:
          replicaCount: 2
