apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributedCluster
metadata:
  labels:
    app.kubernetes.io/name: victoriametrics-operator
  name: vmdistributedcluster-sample-custom-timeout
spec:
  readyDeadline: 10m
  zoneUpdatePause: 1m
  vmagent:
    name: vmagent-sample
  vmusers:
    - name: vmuser-us-east-1
    - name: vmuser-us-west-2
    - name: vmuser-eu-west-1
  zones:
    vmclusters:
    - ref: vmcluster-us-east-1
      overrideSpec:
        vmselect:
          replicaCount: 3
    - ref: vmcluster-us-west-2
      overrideSpec:
        vmselect:
          replicaCount: 4
    - ref: vmcluster-eu-west-1
      overrideSpec:
        vmselect:
          replicaCount: 2
