apiVersion: operator.victoriametrics.com/v1alpha1
kind: VMDistributed
metadata:
  name: VMDistributed-sample-override-global
spec:
  vmagent:
    name: global-write-vmagent
    spec:
      replicaCount: 1
  vmauth:
    name: global-read-vmauth
    spec:
      replicaCount: 1
  zones:
    globalOverrideSpec:
      clusterVersion: v1.90.0
    vmclusters:
    - ref:
        name: vmcluster-us-east-1
    - ref:
        name: vmcluster-us-west-2
    - ref:
        name: vmcluster-eu-west-1
