render:
  kubernetesVersion: '1.35'

processor:
  ignoreTypes:
    - ".*List$"
  ignoreFields:
    - "status$"
    - "TypeMeta$"
  customMarkers:
    - name: deprecated
      target: field
      hasValue: true
